[package]
name = "prooheckcp/roquest"
description = "RoQuest is a sophisticated abstract implementation of a Quest System. Although it can self manage nearly everything it also allows for the developer to manually set and manage everything. API: prooheckcp.github.io/RoQuest/"
version = "0.1.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Prooheckcp"]
exclude = ["**"]
include = [
    "default.project.json", 
    "RoQuest", 
    "RoQuest/*",
    "wally.lock", 
    "wally.toml",
]